import type { PatchProfileExclusion } from "./contract.js";

export const STOCK_CLIENT_POLICY_CANDIDATE_TAGS = [
	"bash-prompt",
	"built-in-agent-prompt",
	"claude-api-scope",
	"claudemd-strong",
	"memory-prompt-soften",
	"mcp-server-name",
	"session-guidance",
	"todo-use",
	"cache-tail-policy",
	"edit-extended",
	"effort-stack",
	"feature-flags",
	"image-limits",
	"tools-off-desktop",
	"no-autoupdate",
	"read-bat",
	"agents-off",
	"commands-off",
	"lsp-multi-server",
	"lsp-filename-schema",
	"skill-paths-invoke",
	"skill-global-paths",
	"skill-listing-ui",
	"subagent-system-prompt",
	"session-mem",
	"sys-prompt-file",
	"limits",
	"prompt-dash-style",
	"workflow-safety",
	"signature",
] as const;

export const STOCK_CLIENT_POLICY_EXCLUSIONS = [
	{ tag: "child-network-env", reason: "provider-routing" },
	{ tag: "file-link-targets", reason: "terminal-only" },
	{ tag: "billing-label", reason: "terminal-only" },
	{ tag: "plan-diff-ui", reason: "terminal-only" },
	{ tag: "plan-compact-execute", reason: "terminal-only" },
	{ tag: "tools-off", reason: "conflicting-tool-policy" },
	{ tag: "configured-model-catalog", reason: "provider-routing" },
	{ tag: "no-collapse", reason: "terminal-only" },
	{ tag: "skill-activation-notice", reason: "terminal-only" },
	{ tag: "agent-listing-ui", reason: "terminal-only" },
	{ tag: "model-aliases", reason: "provider-routing" },
	{ tag: "model-picker-session-only", reason: "terminal-only" },
	{ tag: "subagent-model-tag", reason: "provider-routing" },
	{ tag: "tab-queue", reason: "terminal-only" },
	{ tag: "model-context-metadata", reason: "provider-routing" },
] as const satisfies readonly PatchProfileExclusion[];
